[package]
name = "isla-testgen"
version = "0.1.0"
authors = ["Brian Campbell <Brian.Campbell@ed.ac.uk>"]
edition = "2018"
license = "MIT"

[dependencies]
crossbeam = "0.7.3"
isla-lib = { path = "../isla-lib" }
rand = "0.7.3"
regex = "1.3.1"
